config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
end

app/models/admin.rb
class Admin < Role
  belongs_to :parent, class_name: self.superclass.name, foreign_key: 'id'
end

app/models/developer.rb
class Developer < Employee
  belongs_to :parent, class_name: self.superclass.name, foreign_key: 'id'
end

app/models/employee.rb
class Employee < Role
  belongs_to :parent, class_name: self.superclass.name, foreign_key: 'id'
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user

  after_save :set_association

  def set_association
    self.parent = self.class.new unless self.class == Role
  end

  def what_role?
    puts self.class.name
    parent.what_role? unless self.class != Role
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  has_many :roles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json  { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json  { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HashBang</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p>
  <%= link_to 'New User', new_user_path %>
</p>

<% @users.each do |user| %>
  <%= user.first_name %>  <%= user.surname %> - <%= link_to 'remove', user, :method => :delete %><br/>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <%= link_to 'Show all', users_path %>
</p>

<%= @user.first_name %>